title: Starbuck's Lair Rules
author: The Managers of Starbuck's Lair

description: > # this means to ignore newlines until "baseurl:"
  This website goes over the rules for Starbuck's Lair.
  If you have suggestions for a change to the rules, please visit
  https://github.com/jordguitarflasheart/starbucksrules and open a issue.

theme: minima
